[project]
name = 'gov-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.governance-core]
path = 'contracts/governance-core.clar'
clarity_version = 3
epoch = 3.0

[contracts.proposal-management]
path = 'contracts/proposal-management.clar'
clarity_version = 3
epoch = 3.0

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.tech-gov-token]
path = 'contracts/tech-gov-token.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
